appDefault:
    resource: "@AppBundle/Resources/config/routing/default.yml"
    prefix:  /
    
appVehicle:
    resource: "@AppBundle/Resources/config/routing/vehicle.yml"
    prefix: /vehicle
    
appReserve:
    resource: "@AppBundle/Resources/config/routing/reserve.yml"
    prefix: /reserve
